### ISSUE TITLE
Unable to Process templates

### ISSUE THREAD

**Issue by btjd** [openshift/openshift-restclient-python#100]
Here is the curl command and the correct output:

>   curl -k \
>     -X POST \
>     -d @<path>/jenkins-ephemeral-template.json \
>     -H "Authorization: Bearer <token>" \
>     -H 'Accept: application/json' \
>     -H 'Content-Type: application/json' \
>     https://localhost:8443/oapi/v1/processedtemplates
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "jenkins-ephemeral",
    "selfLink": "/oapi/v1/namespaces//processedtemplates/jenkins-ephemeral",
    "creationTimestamp": null,
    "annotations": {
      "description": "Jenkins service, without persistent storage.\n\nWARNING: Any data stored will be lost upon pod destruction. Only use this template for testing.",
      "iconClass": "icon-jenkins",
      "openshift.io/display-name": "Jenkins (Ephemeral)",
      "tags": "instant-app,jenkins",
      "template.openshift.io/documentation-url": "https://docs.openshift.org/latest/using_images/other_images/jenkins.html",
      "template.openshift.io/long-description": "This template deploys a Jenkins server capable of managing OpenShift Pipeline builds and supporting OpenShift-based oauth login.  The Jenkins configuration is stored in non-persistent storage, so this configuration should be used for experimental purposes only.",
      "template.openshift.io/provider-display-name": "Red Hat, Inc.",
      "template.openshift.io/support-url": "https://access.redhat.com"
    }
  },
  "message": "A Jenkins service has been created in your project.  Log into Jenkins with your OpenShift account.  The tutorial at https://github.com/openshift/origin/blob/master/examples/jenkins/README.md contains more information about using this template.",
  "objects": [
    {
      "apiVersion": "v1",
      "kind": "Route",
      "metadata": {
        "annotations": {
          "template.openshift.io/expose-uri": "http://{.spec.host}{.spec.path}"
        },
        "creationTimestamp": null,
        "labels": {
          "template": "jenkins-ephemeral-template"
        },
        "name": "jenkins"
      },
      "spec": {
        "tls": {
          "insecureEdgeTerminationPolicy": "Redirect",
          "termination": "edge"
        },
        "to": {
          "kind": "Service",
          "name": "jenkins"
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "DeploymentConfig",
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "template": "jenkins-ephemeral-template"
        },
        "name": "jenkins"
      },
      "spec": {
        "replicas": 1,
        "selector": {
          "name": "jenkins"
        },
        "strategy": {
          "type": "Recreate"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "jenkins"
            }
          },
          "spec": {
            "containers": [
              {
                "capabilities": {},
                "env": [
                  {
                    "name": "OPENSHIFT_ENABLE_OAUTH",
                    "value": "true"
                  },
                  {
                    "name": "OPENSHIFT_ENABLE_REDIRECT_PROMPT",
                    "value": "true"
                  },
                  {
                    "name": "OPENSHIFT_JENKINS_JVM_ARCH",
                    "value": "i386"
                  },
                  {
                    "name": "KUBERNETES_MASTER",
                    "value": "https://kubernetes.default:443"
                  },
                  {
                    "name": "KUBERNETES_TRUST_CERTIFICATES",
                    "value": "true"
                  },
                  {
                    "name": "JNLP_SERVICE_NAME",
                    "value": "jenkins-jnlp"
                  }
                ],
                "image": " ",
                "imagePullPolicy": "IfNotPresent",
                "livenessProbe": {
                  "failureThreshold": 30,
                  "httpGet": {
                    "path": "/login",
                    "port": 8080
                  },
                  "initialDelaySeconds": 420,
                  "timeoutSeconds": 3
                },
                "name": "jenkins",
                "readinessProbe": {
                  "httpGet": {
                    "path": "/login",
                    "port": 8080
                  },
                  "initialDelaySeconds": 3,
                  "timeoutSeconds": 3
                },
                "resources": {
                  "limits": {
                    "memory": "512Mi"
                  }
                },
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                },
                "terminationMessagePath": "/dev/termination-log",
                "volumeMounts": [
                  {
                    "mountPath": "/var/lib/jenkins",
                    "name": "jenkins-data"
                  }
                ]
              }
            ],
            "dnsPolicy": "ClusterFirst",
            "restartPolicy": "Always",
            "serviceAccountName": "jenkins",
            "volumes": [
              {
                "emptyDir": {
                  "medium": ""
                },
                "name": "jenkins-data"
              }
            ]
          }
        },
        "triggers": [
          {
            "imageChangeParams": {
              "automatic": true,
              "containerNames": [
                "jenkins"
              ],
              "from": {
                "kind": "ImageStreamTag",
                "name": "jenkins:latest",
                "namespace": "openshift"
              },
              "lastTriggeredImage": ""
            },
            "type": "ImageChange"
          },
          {
            "type": "ConfigChange"
          }
        ]
      }
    },
    {
      "apiVersion": "v1",
      "kind": "ServiceAccount",
      "metadata": {
        "annotations": {
          "serviceaccounts.openshift.io/oauth-redirectreference.jenkins": "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"jenkins\"}}"
        },
        "labels": {
          "template": "jenkins-ephemeral-template"
        },
        "name": "jenkins"
      }
    },
    {
      "apiVersion": "v1",
      "groupNames": null,
      "kind": "RoleBinding",
      "metadata": {
        "labels": {
          "template": "jenkins-ephemeral-template"
        },
        "name": "jenkins_edit"
      },
      "roleRef": {
        "name": "edit"
      },
      "subjects": [
        {
          "kind": "ServiceAccount",
          "name": "jenkins"
        }
      ]
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "labels": {
          "template": "jenkins-ephemeral-template"
        },
        "name": "jenkins-jnlp"
      },
      "spec": {
        "ports": [
          {
            "name": "agent",
            "nodePort": 0,
            "port": 50000,
            "protocol": "TCP",
            "targetPort": 50000
          }
        ],
        "selector": {
          "name": "jenkins"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "annotations": {
          "service.alpha.openshift.io/dependencies": "[{\"name\": \"jenkins-jnlp\", \"namespace\": \"\", \"kind\": \"Service\"}]",
          "service.openshift.io/infrastructure": "true"
        },
        "creationTimestamp": null,
        "labels": {
          "template": "jenkins-ephemeral-template"
        },
        "name": "jenkins"
      },
      "spec": {
        "ports": [
          {
            "name": "web",
            "nodePort": 0,
            "port": 80,
            "protocol": "TCP",
            "targetPort": 8080
          }
        ],
        "selector": {
          "name": "jenkins"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
      }
    }
  ],
  "parameters": [
    {
      "name": "JENKINS_SERVICE_NAME",
      "displayName": "Jenkins Service Name",
      "description": "The name of the OpenShift Service exposed for the Jenkins container.",
      "value": "jenkins"
    },
    {
      "name": "JNLP_SERVICE_NAME",
      "displayName": "Jenkins JNLP Service Name",
      "description": "The name of the service used for master/slave communication.",
      "value": "jenkins-jnlp"
    },
    {
      "name": "ENABLE_OAUTH",
      "displayName": "Enable OAuth in Jenkins",
      "description": "Whether to enable OAuth OpenShift integration. If false, the static account 'admin' will be initialized with the password 'password'.",
      "value": "true"
    },
    {
      "name": "JVM_ARCH",
      "displayName": "Jenkins JVM Architecture",
      "description": "Whether Jenkins runs with a 32 bit (i386) or 64 bit (x86_64) JVM.",
      "value": "i386"
    },
    {
      "name": "MEMORY_LIMIT",
      "displayName": "Memory Limit",
      "description": "Maximum amount of memory the container can use.",
      "value": "512Mi"
    },
    {
      "name": "NAMESPACE",
      "displayName": "Jenkins ImageStream Namespace",
      "description": "The OpenShift Namespace where the Jenkins ImageStream resides.",
      "value": "openshift"
    },
    {
      "name": "JENKINS_IMAGE_STREAM_TAG",
      "displayName": "Jenkins ImageStreamTag",
      "description": "Name of the ImageStreamTag to be used for the Jenkins image.",
      "value": "jenkins:latest"
    }
  ],
  "labels": {
    "template": "jenkins-ephemeral-template"
  }
}

Here is the code I am trying to use to process the template using the client:
```
from openshift import config
from openshift import client as ocpclient
from kubernetes import client as k8sclient
from kubernetes.client.rest import ApiException
from pprint import pprint
import json

namespace = 'default'
pretty = 'pretty_example'

# Load default kube config
config.load_kube_config()

# Process the template to replace variables with concrete values
api = ocpclient.OapiApi()
with open('templates/jenkins-ephemeral-template.json') as jf:
    template_dict = json.load(jf)

# pprint(template_dict)

try:
    processed_template_dict = api.create_namespaced_processed_template(namespace, template_dict, pretty=pretty)
    pprint(processed_template_dict)
except ApiException as e:
    print("Exception when calling OapiApi->create_namespaced_processed_template: %s\n" % e)
```
The resulting output is:

> Exception when calling OapiApi->create_namespaced_processed_template: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 04 Oct 2017 20:01:25 GMT', 'Content-Length': '174', 'Content-Type': 'application/json', 'Cache-Control': 'no-store'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

When using the method "create_processed_template_for_all_namespaces_v1" instead:
```
try:
    processed_template_dict = api.create_processed_template_for_all_namespaces_v1(template_dict, pretty=pretty)
    pprint(processed_template_dict)
except ApiException as e:
    print("Exception when calling OapiApi->create_namespaced_processed_template: %s\n" % e)
```
I get:

> {'api_version': 'v1',
 'kind': 'Template',
 'labels': None,
 'message': None,
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': {},
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'name': 'fio',
              'namespace': None,
              'owner_references': None,
              'resource_version': None,
              'self_link': '/oapi/v1/namespaces//processedtemplates/fio',
              'uid': None},
 **'objects': [{'raw': None}, {'raw': None}, {'raw': None}, {'raw': None}],**
 'parameters': [{'_from': None,
                 'description': 'The name assigned to all of the frontend objects defined in this template.',
                 'display_name': 'Name',
                 'generate': None,
                 'name': 'NAME',
                 'required': True,
                 'value': 'fio'},
                {'_from': None,
                 'description': 'Volume space available for data, e.g. 512Mi, 2Gi',
                 'display_name': 'Volume Capacity',
                 'generate': None,
                 'name': 'VOLUME_CAPACITY',
                 'required': True,
                 'value': '1Gi'},
                {'_from': None,
                 'description': 'Storage class to create PVC from.',
                 'display_name': None,
                 'generate': None,
                 'name': 'STORAGECLASS_NAME',
                 'required': None,
                 'value': 'default'},
                {'_from': '[a-z0-9]{10}',
                 'description': 'Random string add on for PVC.',
                 'display_name': 'PVC String Add on',
                 'generate': 'expression',
                 'name': 'PVC_STRING',
                 'required': None,
                 'value': 'ean7m5npvt'},
                {'_from': None,
                 'description': 'The file that you want downloaded that specifies FIO parameters.',
                 'display_name': 'FIO File',
                 'generate': None,
                 'name': 'FIO_FILE',
                 'required': None,
                 'value': 'https://<repo-path>/raw/master/apps/FIO/ini/fio.ini'}]}

**Comment by fabianvf** [comment]
The new [dynamic client](https://github.com/openshift/openshift-restclient-python/blob/master/README.md#dynamic-client-usage) should be able to handle this properly, it will just pass your resources through to the server.
