### ISSUE TITLE
kubernetes apis and models inaccessible through openshift client

### ISSUE THREAD

**Issue by btjd** [openshift/openshift-restclient-python#101]
I believe it should be possible to access kubernetes apis and models directly through and openshift client instance, but that seems to be broken.

```
>>> from openshift import config
>>> from openshift import client as ocpclient
>>> from kubernetes import client as k8sclient
>>> config.load_kube_config()
>>> api_instance = ocpclient.CoreV1Api()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'CoreV1Api'
>>> api_instance = k8sclient.CoreV1Api()
>>> print(api_instance)
<kubernetes.client.apis.core_v1_api.CoreV1Api object at 0x7f9b2cb037d0>
```

**Comment by fabianvf** [comment]
I verified that this was not the behavior previous to the module generation changes, so I'm marking it as an enhancement.

I can see the rationale behind wanting a unified openshift/kubernetes client, though I'm not sure how I feel about actually implementing it here. It might be strange to be doing openshift.client.CoreV1Api() and get back a kubernetes.client.apis.core_v1_api.CoreV1Api object. I'm also a little worried about possible conflicts between kubernetes and openshift APIs/models, particularly with the RBAC stuff which caused some trouble for me when setting up generation.

 I don't really have strong feelings on it though, I'd love for some more people to chime in. I don't think this is a high priority, but I'd be open to adding it after the 3.7 release goes out.

**Comment by btjd** [comment]
Thanks for looking into this. Obviously there is a workaround and I feel it's fair to mark this as an enhancement. I am working in a script that implements oc new-app and it would just be nicer to access all the objects and methods from the same client.

**Comment by djzager** [comment]
https://github.com/openshift/openshift-restclient-python#dynamic-client-usage now gives you the unified client.
