### ISSUE TITLE
Need to filter log information in ansible helper

### ISSUE THREAD

**Issue by abadger** [openshift/openshift-restclient-python#107]
The ansible helper code: https://github.com/openshift/openshift-restclient-python/blob/master/openshift/helper/ansible.py creates its own log objects and then proceeds to pass data that came into the AnsibleModule into this object.  This can be dangerous as some of the data could be sensitive information that should not be logged (example: passwords and other credentials).

The module author can specify things that should not be logged by marking an AnsibleModule parameter as no_log.  The helper function that logs how the module was invoked seems to use that for stripping the sensitive information from the log: https://github.com/openshift/openshift-restclient-python/blob/master/openshift/helper/ansible.py#L175.  However, it does not use the information to strip that information anywhere else that logging is called.  (For instance, if an http request is constructed with the sensitive information and then the request body is logged).

The end user may also specify that a task should not be logged via no_log: True in an ansible playbook.  This setting is not used at all in the openshift/helper/ansible.py code.

In Ansible's code base we're currently carrying two module_utils files that make use of this library but no modules using it.  We're thinking of several ways to mitigate the problem in the module_utils files (for instance, removing the debug parameter so users can't turn on the logging and/or switching the module_utils to use AnsibleModule.log() which takes these issues into account).  However, we cannot touch the issues in this code, nor prevent a module from switching debugging back on.  I'm opening this bug so that you can take steps, if you wish, to mitigate this in your own code (ideally, I think, by filtering all values that are sent to be logged similar to what AnsibleModule does, or using AnsibleModule's logging instead of creating your own logger.)

**Comment by fabianvf** [comment]
Good catch, this definitely needs to be resolved. I'll try and find some time this week to dig into it.

**Comment by chouseknecht** [comment]
@fabianvf @abadger 

In the new Ansible modules, did the following to address the security concerns mentioned above:

- Removed `diff` and `request_body` data from the module output in [Ansible #34230](https://github.com/ansible/ansible/pull/34230).
- Specifically for Secrets, removed `data', `string_data`, and things that smell like sensitive data found in annotations as part of [Ansible #34229](https://github.com/ansible/ansible/pull/34229)
- Module parameters that should be considered sensitive have the `no_log` attribute
- All logging mechanisms outside of standard `module.exit_json()` were removed

**Comment by towolf** [comment]
@chouseknecht that is really a shame.

Why remove diff when it should be up to the user???

No `--diff`, no problem.

**Comment by fabianvf** [comment]
The Ansible logic has all been moved into the Ansible project
