### ISSUE TITLE
 k8s_v1_secret outputs the secrets

### ISSUE THREAD

**Issue by fabianvf** [openshift/openshift-restclient-python#117]
Cloned from ansible/ansible-kubernetes-modules#17

Using the k8s_v1_secret module results output like this:

changed: [host] => (item={'name': 'secret-name', 'user': 'username', 'pass': 'password'})

This output is also saved in the logs. I think the secrets should be hidden.

@derfred , @awiddersheim : I've cloned this issue to this repo because this is where the logic that the ansible-kubernetes-modules rely on is defined.

**Comment by chouseknecht** [comment]
@fabianvf 

Does https://github.com/ansible/ansible/pull/34229 address this issue sufficiently in the new modules?

**Comment by djzager** [comment]
https://github.com/ansible/ansible-kubernetes-modules/issues/17#issuecomment-340490926
