### ISSUE TITLE
Support for Creating Custom Resource Definitions

### ISSUE THREAD

**Issue by rahulinux** [openshift/openshift-restclient-python#120]
Openshift module uses, kubernetes==3.0.0, which does not have ApiextensionsV1beta1Api, it's available in kubernetes==4.0.0a1.

How to work with custom resources ?

**Comment by fabianvf** [comment]
these modules target kubernetes 1.7 at the moment, they would just need to be regenerated against 1.8 (3.0.0 targets 1.7, 4.0.0 targets 1.8). Unfortunately generation for 1.8 is broken right now as a result of some changes to the way kubernetes generates its modules. The updated modules are definitely on my plate, and I would guess they'll land sometime in the next few weeks, just need to clear some time so I can dive in and fix the generation.

**Comment by fabianvf** [comment]
If you have a sample ansible task for custom resources though, it would make it a lot easier for me to test this specific functionality as I regen the modules.

**Comment by rahulinux** [comment]
I'm trying to deploy prometheus operator, all things went well until new `apiVersion` and `Kind` Example: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml

**Comment by fabianvf** [comment]
Ah I see, this is a little tougher than I thought... the modules are generated against a static API spec so I doubt regenning the modules would help with this case. I'll have to look further into this, it may require some specialized logic to get the ansible modules to support it properly.

**Comment by rahulinux** [comment]
I come up with following solution, which is working fine. 

```
class CustomResource(object):
    def __init__(self):
        config = client.Configuration()
        if not config.api_client:
            config.api_client = client.ApiClient()
        self.api_client = config.api_client

    def run(self, body, namespace='default', domain=None,api_version=None,kind=None):
        resource_path = '/apis/' + domain + '/' + api_version +  '/namespaces/' +  namespace + '/' + kind
        header_params = {}
        header_params['Accept'] = self.api_client.select_header_accept(['application/json'])
        header_params['Content-Type'] = self.api_client.select_header_content_type(['*/*'])

        (resp, code, header) = self.api_client.call_api(
                resource_path, 'GET', { 'namespace': namespace}, {}, header_params, body, [], _preload_content=False)
        data =  json.loads(resp.data.decode('utf-8'))

        if body.get('state') == 'present':
           # Check if already exists
           for i in data['items']:
              if i['metadata']['name'] == body['metadata']['name']:
                 header_params['Content-Type'] = self.api_client.select_header_content_type(['application/merge-patch+json'])
                 resource_path = i['metadata']['selfLink']
                 (resp, code, header) = self.api_client.call_api(
                   resource_path, 'PATCH', { 'name': 'prometheus', 'namespace': namespace }, {}, header_params, body, [], _preload_content=True)
                 if code == 200:
                    return json.dumps(dict(status="Successfully Updated"))
                 return json.dumps(dict(status="Something wrong with patch object"))
           else:
              (resp, code, header) = self.api_client.call_api(
                   resource_path, 'POST', { 'namespace': namespace}, {}, header_params, body, [], _preload_content=False)
              if code == 201:
                 return json.dumps(dict(status="Successfully added"))
              return json.dumps(dict(status="Something went wrong with add object"))

        elif body.get('state') == 'absent':
           body['kind'] = 'DeleteOptions'
           (resp, code, header) = self.api_client.call_api(
                   resource_path, 'DELETE', {'namespace': namespace}, {}, header_params, body, [], _preload_content=False)
           data = json.loads(resp.data.decode('utf-8'))
           if  data['items'] == []:
                 return json.dumps(dict(status="Already deleted"))
           return json.dumps(dict(status="Successfully Deleted"))

        return json.loads(resp.data.decode('utf-8'))


def k8s_prometheus(data):
    config.load_kube_config()
    data['metadata'] = { 'name': data.get('name'),
                         'namespace': data.get('namespace'),
                         'labels': data.get('labels') }
    del data['labels']
    del data['namespace']
    api = CustomResource()
    kinds = { 'ServiceMonitor' : 'servicemonitors',
              'Prometheus': 'prometheuses',
              'Alertmanager': 'alertmanagers' }
    api_response = api.run(body=data,domain='monitoring.coreos.com',
            api_version='v1',kind=kinds.get(data.get('kind')),namespace='monitoring') 
    if 'success' in api_response.lower():
        return (True,api_response)
    return (False,api_response)
```

Ansible exmaple:

```
- name: creating service monitor for node-exporter
  k8s_promethues:
     state: '{{ state }}'
     name: node-exporter
     namespace: monitoring
     kind: ServiceMonitor
     labels:
       k8s-app: node-exporter
     spec:
       jobLabel: k8s-app
       selector:
         matchLabels:
           k8s-app: node-exporter
       namespaceSelector:
         matchNames:
         - monitoring
       endpoints:
       - port: http-metrics
         interval: 30s
```

**Comment by chouseknecht** [comment]
@fabianvf 

Looking at the provided K8s [example of a CRD here](https://github.com/kubernetes/sample-controller), and trying to wrap my head around the problem...

It seems like having a module that manages the create/delete/update of the [crd.yml](https://github.com/kubernetes/sample-controller/blob/master/artifacts/examples/crd.yaml) is probably not very useful. The real thing folks want, and I think it's reflected in this issue, is the ability to manage the actual custom objects. So in this case, we want to manage a Prometheus object. 

There's an API and List model for discovering the available custom resources, which would provide a list of API group/version and Kind. That seems simple enough. But, how would you go about getting the struct of the model, and the available methods for a custom type?

**Comment by chouseknecht** [comment]
@fabianvf 

I do see that there is a [validation type model here](https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/client/models/v1beta1_custom_resource_validation.py). Maybe that's the key to getting the model struct?

**Comment by djzager** [comment]
This is addressed by adding the dynamic client (https://github.com/openshift/openshift-restclient-python/pull/167) as well as the `k8s` module (https://docs.ansible.com/ansible/devel/modules/k8s_module.html).
