### ISSUE TITLE
Client changes types when parsing IntOrString

### ISSUE THREAD

**Issue by joshbenner** [openshift/openshift-restclient-python#131]
When deserializing, the client parses values that swagger defines as `io.k8s.apimachinery.pkg.util.intstr.IntOrString` as only a string. This causes problems if you read an object, modify, then try to re-upload it in some cases.

Specifically, I hit this when reading a deployment, adding an attribute, and updating it (via ansible.kubernetes-modules). My strategy.rolling_update.max_surge in Kubernetes is integer `1`, but when the client deserializes, it coerces that value to a string. When that is then sent back to k8s, I get an error because if maxSurge is a string, it should have a `%` character at the end.

**Comment by djzager** [comment]
This is addressed by adding the dynamic client (#167) as well as the k8s module (https://docs.ansible.com/ansible/devel/modules/k8s_module.html).

You will need to use the dynamic client (https://github.com/openshift/openshift-restclient-python#dynamic-client-usage).
