### ISSUE TITLE
4.0 breaks module parameter generation

### ISSUE THREAD

**Issue by chouseknecht** [openshift/openshift-restclient-python#141]
We rely on the `swagger_types` property in the models for generating module parameters, and for translating a config template into a Python object.

Consider the new swagger spec for V1DeploymentStrategy. Its swagger type has 2 properties: `type`, and `rolling_update`. If we see a `type` property, we know that there are multiple options for a type, and we expect each option be included in `swagger_types` in the form of `X_params`. Look at [V1DeploymentStrategy in version 3.4](https://github.com/openshift/openshift-restclient-python/blob/release-0.3.4/openshift/client/models/v1_deployment_strategy.py), and you will see 3 `X_params` options. We know those are the 3 choices for type, and we know the model for constructing the attributes of each param object.

Compare that to the new version. All the new version has is `rolling_update`, which doesn't line up at all with how our code works. Even the name `rolling_update` does not match with the actual value that API expects for a type. The API expects to see one of `rolling`, `recreate`, or `custom`, and it expects to receive a corresponding `X_params` value.

I have no idea how to fix this, without hard coding things to fill in the gaps left by the new swagger spec files.

**Comment by fabianvf** [comment]
Think this was an issue with module generation, looks like it's fixed in the current 0.4 branch. Reopen if you disagree: https://github.com/openshift/openshift-restclient-python/blob/release-0.4/openshift/client/models/v1_deployment_strategy.py
