### ISSUE TITLE
Version scheme lacks documentation, difficult to tell what versions of openshift/kubernetes/kubernetes client are supported

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-restclient-python#152]
I didn't find an explanation in the readme, and I'm wondering if the rest client versions have any relation to the OpenShift versions at all.

**Comment by dlbewley** [comment]
Looks like my answer is in here as far as k8s. I imagine YMMV when it comes to OpenShift feature parity. https://github.com/kubernetes-client/python#compatibility

**Comment by fabianvf** [comment]
Openshift 3.x should have parity with Kubernetes 1.x, and our client's 0.x has parity with the kubernetes client's major version (ie, our 0.4 is generated using their 4.0). I should make that clear in the docs though, thanks for pointing this out.

**Comment by dlbewley** [comment]
Got it. OpenShift client `0.x` matches Kubernetes client `x.0`. It wasn't clear on the relationship to server and why the versioning is so different.

It appears that client to server mappings are:

- `3.0 is k8s <=1.7` == `0.3 is ocp <= 3.7`
- `4.0 is k8s <= 1.8` == `0.4 is ocp <= 3.8`
- `5.0 is k8s <= 1.9` == `0.5 is ocp <= 3.9`

**Comment by fabianvf** [comment]
Yes, that is correct
