### ISSUE TITLE
Resources with stripped prefixes can't be found with their group+version+kind

### ISSUE THREAD

**Issue by honkycat** [openshift/openshift-restclient-python#162]
Currently, the Ingress resource is missing from client/model, causing the error `V1Ingress was not found in client.models. Did you specify the correct Kind and API Version?"`

**Comment by msnelling** [comment]
I'm also seeing the same for ExtensionsV1beta1Ingress, i'm on Kubernetes version 1.9.6

**Comment by djzager** [comment]
If you could provide a code snippet, that would be helpful. However, I believe that `Ingress` in general is a Kubernetes object https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1beta1Ingress.md and would not be found in the OpenShift models. As far as I understand, that would explain your issue.

I trust @fabianvf can correct me if I am wrong.

**Comment by fabianvf** [comment]
copied from the ansible issue:
> The openshift client actually falls back to the kubernetes client when a resource is not found. This error is a result of the group+version+kind not being found inside the kubernetes resources, because during code generation the group is stripped off.
> The helpers are looking for ExtensionsV1beta1Ingress but the actual model that is generated is V1beta1Ingress instead (located here: https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/v1beta1_ingress.py)
> I think if you change the apiVersion in your template to v1beta1 instead of extensions/v1beta1 you will be able to progress. That being said it's still bad behavior, so I think the actual bug here is that when we look for the model we should attempt to compensate for the stripped prefixes so that we support unmodified resource definitions.

To address your concerns with the general approach, the openshift client helpers make full use of the kubernetes client, they just add the openshift models and include helpers for interacting with the generated kubernetes and openshift resources. There should be no divergence from the resources supported by the openshift client helpers and the generated kubernetes client.

**Comment by djzager** [comment]
For my sanity, the ansible issue being mentioned is https://github.com/ansible/ansible/issues/38296 .

Thank you @fabianvf. I did not realize that this was referring to helper functionality. The error message comes from https://github.com/openshift/openshift-restclient-python/blob/2a798cd7f2a9d6d36c8d4a50f21f6f780ef860dd/openshift/helper/base.py#L521.

In the meantime @honkycat, a way to work around this is to remove the `extensions/` from `"extensions/v1beta1"`. As an example, [here](https://github.com/djzager/automation-broker-apb/blob/5837b9252f358749ee9964ccb4559f07ea161454/templates/broker-auth.clusterrole.yaml#L3-L4) I am creating a clusterrole. Sorry for not catching on more quickly. Thank you for bringing this issue up.
