### ISSUE TITLE
Python3.7 compatibility: async is a reserved keyword

### ISSUE THREAD

**Issue by Chive** [openshift/openshift-restclient-python#183]
Hi all, 

While trying to import the library with python3.7, the following error occurs:

```
  File "/virtualenv/lib/python3.7/site-packages/openshift/__init__.py", line 15, in <module>
    import openshift.client
  File "/virtualenv/lib/python3.7/site-packages/openshift/client/__init__.py", line 221, in <module>
    from .apis.apps_openshift_io_api import AppsOpenshiftIoApi
  File "/virtualenv/lib/python3.7/site-packages/openshift/client/apis/__init__.py", line 4, in <module>
    from .apps_openshift_io_api import AppsOpenshiftIoApi
  File "/virtualenv/lib/python3.7/site-packages/openshift/client/apis/apps_openshift_io_api.py", line 120
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

This has already been fixed in the upstream here https://github.com/kubernetes-client/python/pull/568.

**Comment by fabianvf** [comment]
I think this will also affect the dynamic implementation. We will need to base this against the not yet released kubernetes python client, so we will need to wait for 7.0 to come out before we can actually ship this.

Also side note for @Chive, we are deprecating the generated openshift modules in favor of a dynamic implementation found in openshift/dynamic/client.py. It still makes use of the kubernetes client but has a generic interface for discovering and interacting with resources.

**Comment by pvdvreede** [comment]
7.0.0 came out a day ago, so is this issue able to be actioned now? thanks.

**Comment by dbazhal** [comment]
Tx for fixing this, well done!

**Comment by pvdvreede** [comment]
Great! Many thanks for the quick attention to this.

**Comment by fabianvf** [comment]
No problem, thanks for bringing it to my attention!
