### ISSUE TITLE
Attribute error raised when reusing resources from API client

### ISSUE THREAD

**Issue by fridex** [openshift/openshift-restclient-python#184]
When I'm trying to reuse responses from the API client, I'm receiving unexpected attribute error:

Consider a code like this - I'm assuming there is a template present in the given namespace from which I'm trying to create a pod:

```python
from kubernetes import client, config
from openshift.dynamic import DynamicClient

config.load_incluster_config()
dyn_client = DynamicClient(client.ApiClient())

result = dyn_client.resources.get(api_version='v1', kind='Template').get(namespace='my-namespace')

object = result.items[0].objects[0]

dyn_client.resources.get(api_version='v1', kind='Pod').create(body=object, namespace='my-namespace')
```

This code throws:

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 31, in inner
    resp = func(self, resource, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 161, in create
    return self.request('post', path, body=body, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 255, in request
    _return_http_data_only=params.get('_return_http_data_only', True)
  File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 144, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in sanitize_for_serialization
    for key, val in iteritems(obj_dict)}
  File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 213, in <dictcomp>
    for key, val in iteritems(obj_dict)}
  File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 209, in sanitize_for_serialization
    for attr, _ in iteritems(obj.swagger_types)
  File "/opt/app-root/lib/python3.6/site-packages/six.py", line 581, in iteritems
    return iter(d.items(**kw))
AttributeError: 'NoneType' object has no attribute 'items'
```

The exception is thrown because there are created `ResourceFields` that are subsequently tried to be serialized in the `sanitize_for_serialization` method in class `kubernetes.client.api_client.ApiClient` where there is tried to retrieve `swagger_types` property (kubernetes library does not know how to serialize OpenShift `ResourceFields`). As this property does not exist, the `ResourceFields` behavior for non-existing attributes returns `None` and the exception is thrown.

A workaround for this is to use `ResourceInstance.to_dict`:

```python3
dyn_client.resources.get(api_version='v1', kind='Pod').create(body=result.to_dict()['items'][0]['objects'][0], namespace='my-namespace')
```

This is not really a bug but IMHO worth to document behavior.

**Comment by fabianvf** [comment]
which version of the kubernetes and openshift Python libraries are you using?

**Comment by fabianvf** [comment]
As for whether the template can be processed, the templating logic may only exist in the `oc` client binary, in which case the dynamic client wouldn't support it natively (we would have to mimic whatever logic the client uses). I'll see if I can find where this is happening, it could also be that we're missing some special routes when we do discovery.

**Comment by fridex** [comment]
> which version of the kubernetes and openshift Python libraries are you using?

kubernetes==6.0.0
openshift==0.6.2

> As for whether the template can be processed, the templating logic may only exist in the oc client binary, in which case the dynamic client wouldn't support it natively (we would have to mimic whatever logic the client uses). I'll see if I can find where this is happening, it could also be that we're missing some special routes when we do discovery.

When running the oc binary in verbose mode, I can see there is done a `POST` request to `/apis/template.openshift.io/v1/namespaces/{namespace}/processedtemplates` endpoint (compatibility reasons?)- it is [stated in the docs](https://docs.openshift.com/container-platform/3.5/rest_api/openshift_v1.html#create-a-template), but I somehow missed it (the desc was confusing to me).

**Comment by fabianvf** [comment]
@fridex looked into the processedtemplates endpoint, I think it violates an assumption I made (that Group + Version + Kind leads to a unique resource type). There may be a way to support this but I think I'm going to need to rework some code in the dynamic client

**Comment by fridex** [comment]
@fabianvf cool, thanks! I used the `to_dict()` workaround for now.
