### ISSUE TITLE
Retrieve Resources Without Cluster Specific Data

### ISSUE THREAD

**Issue by fijshion** [openshift/openshift-restclient-python#195]
Sorry if this is obvious. I can't figure out how to use the DynamicClient to retrieve a resource without cluster specific values. This can be done with the CLI via the export flag, e.g. ```oc get services/insights-api -o yaml --export```. Is this possible with the DynamicClient?

**Comment by fijshion** [comment]
Nevermind - this did the trick:

```
    resource = openshift_client.resources.get(
        api_version='v1', kind='Service')
    yaml_str = resource.get(
        name='syslog-ng', namespace=project_name, query_params=[('exact', 'false'), ('export', 'true')])
```

**Comment by fabianvf** [comment]
Oh neat, I didn't know that. Sorry for delayed response, was out on PTO.
