### ISSUE TITLE
V1BuildSchema validation requires node_selector

### ISSUE THREAD

**Issue by dbazhal** [openshift/openshift-restclient-python#200]
Hi.
I'm trying to run build from rest client, like this:
```python
    build_api_client = BuildOpenshiftIoV1Api(
        OpenshiftApiClient(configuration=client_config)
    )
    trigger_cause = V1BuildTriggerCause(message='Manual run')
    build_meta = V1ObjectMeta(name=name, namespace=namespace)
    build_request = V1BuildRequest(
        kind='BuildRequest', api_version='build.openshift.io/v1',
        metadata=build_meta, triggered_by=[trigger_cause, ],
    )
    result = build_api_client.create_namespaced_build_config_instantiate(
        name, namespace, body=build_request
    )
```
And get exception, like this:
```
  File "/home/bajal/git/slice_build_s2i/slice_build_s2i/application.py", line 94, in run
    name, namespace, body=build_request
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/openshift/client/apis/build_openshift_io_v1_api.py", line 939, in create_namespaced_build_config_instantiate
    (data) = self.create_namespaced_build_config_instantiate_with_http_info(name, namespace, body, **kwargs)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/openshift/client/apis/build_openshift_io_v1_api.py", line 1030, in create_namespaced_build_config_instantiate_with_http_info
    collection_formats=collection_formats)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/openshift/client/api_client.py", line 22, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize_model(data, klass)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/openshift/client/api_client.py", line 22, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize_model(data, klass)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/openshift/client/models/v1_build_spec.py", line 78, in __init__
    self.node_selector = node_selector
  File "/home/bajal/venv/slice_build_s2i/lib/python3.7/site-packages/openshift/client/models/v1_build_spec.py", line 138, in node_selector
    raise ValueError("Invalid value for `node_selector`, must not be `None`")
ValueError: Invalid value for `node_selector`, must not be `None`
```

I don't understand - why there should be any node_selector in responce Build object?
It only works if I get an answer by myself, adding _preload_content=False to request - in this case it skips deserialization and throws no node_selector exception.

**Comment by fabianvf** [comment]
Yeah, this is an issue that arises from the OpenAPI schema that the modules are generated from, as it incorrectly claims that the node_selector is a required value. 

As a result of issues like these we've actually implemented a new approach (the dynamic client), which doesn't perform client-side validation and dynamically discovers the resources on the cluster (allowing you to interact with CustomResources/aggregated API servers as well). There are some new examples using the dynamic client in the README. The preload_content=False workaround is the only way other than using the dynamic client. 

We don't currently plan to continue updating the statically generated modules as there were too many issues with the spec to properly maintain them. Our efforts are currently focused on improving the dynamic client.

I think the new code using the dynamic client would probably look like this (forgive any errors, writing this from a meeting and I'm not very familiar with the build APIs):

```python
from kubernetes.client import ApiClient
from openshift.dynamic import DynamicClient

# Do whatever you need for you client configuration object, and pass it to ApiClient(). 
# The dynamic client will use the kubernetes API client for actual interactions.
client = DynamicClient(ApiClient())

v1_buildrequests = client.resources.get(api_version='build.openshift.io/v1', kind='BuildRequest')

# This is just the normal Kubernetes object definition
resource = {
  "apiVersion": "build.openshift.io/v1",
  "kind": "BuildRequest",
  "metadata": {
    "name": name.
    "namespace": namespace
  },
  "spec": {
    "triggeredBy": [{"message": "Manual run"}]
  }
}

result = v1_buildrequests.create(body)
```

**Comment by dbazhal** [comment]
Oh, and one more question - how do I use dynamic client with watch? It looks like it requires ApiClient at the moment. Is it future work?
When I do
```python
    build_api: Resource = dyn_client.resources.get(
        api_version='build.openshift.io/v1', kind='Build'
    )
    for event in w.stream(
        build_api.get,
        namespace=namespace,
        field_selector='metadata.name={}'.format(build_name),
        resource_version=resource_version,
        timeout_seconds=600
    )
```
watcher never yields any events(looks like it isn't matching any objects).

**Comment by dbazhal** [comment]
And you know, I can't use dynclient as simply as in your example. There is no BuildRequest resource, so creating a build is dedicated(not crud) method of build resource(nothing in DynamicClient interface maps me to create_namespaced_build_config_instantiate method of BuildOpenshiftIoV1Api object, so I got to construct request path by myself and it does not look pretty - in this case i could just send requests with pure requests module. It's kinda sad.

**Comment by fabianvf** [comment]
Ah, my apologies, I assumed `BuildRequest` operated similarly to `ProjectRequest`. Looked into it a little closer, I think we still have access to the `/instantiate` subresource like so:

```python
from kubernetes.client import ApiClient
from openshift.dynamic import DynamicClient

name = 'test'
namespace = 'test'

# Do whatever you need for you client configuration object, and pass it to ApiClient(). 
# The dynamic client will use the kubernetes API client for actual interactions.
client = DynamicClient(ApiClient())

v1_buildconfigs = client.resources.get(api_version='build.openshift.io/v1', kind='BuildConfig')

# This is just the normal Kubernetes object definition
resource = {
  "apiVersion": "build.openshift.io/v1",
  "kind": "BuildRequest",
  "metadata": {
    "name": name.
    "namespace": namespace
  },
  "spec": {
    "triggeredBy": [{"message": "Manual run"}]
  }
}

result = v1_buildrconfigs.instantiate.create(resource)
```

Unfortunately I did find a bug related to how I'm handling the `create` method in subresources, I'll try and get that patched today. Sorry for the inconvenience, but I appreciate the report and will try to get it working ASAP. 

I also don't have an answer for your questions surrounding watch at the moment, I'll take a look once the subresource issue is fixed.

**Comment by dbazhal** [comment]
Wow, thank you for your reply, i really appreciate it. Will be waiting for fix to test it.

**Comment by fabianvf** [comment]
So I have a first stab at a fix that I *think* might work, but since I've never used `BuildConfigs` I don't have a good environment for testing it out myself. If you can give me a few examples of the resources required to get a build config + whatever other resources are necessary for it (it looked like you might need to set up an ImageStream?) I can verify it properly. Alternatively, you can install it locally with 

    pip install https://github.com/fabianvf/openshift-restclient-python/archive/instantiate.tar.gz

I don't want to burden you with too many testing loops though, so if it doesn't work right away probably best for me to get an environment set up.

https://github.com/openshift/openshift-restclient-python/pull/201

**Comment by dbazhal** [comment]
Thanks for your fix, replied to it in commit.
Also you can create simple build like this:
```bash
# cat test_build_run.yaml 
kind: Template
apiVersion: v1
metadata:
  name: test_subresources
parameters:
- name: NAMESPACE
- name: NAME
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:latest"
      source:
        type: "Dockerfile"
        dockerfile: "FROM centos:7\nRUN yum install -y httpd"
      strategy:
        type: Docker
# oc process -f test_build_run.yaml NAME=testimage NAMESPACE=testnamespace | oc create -f -
```

**Comment by fabianvf** [comment]
Awesome, thanks so much for filing the issue and helping debug/test that.
