### ISSUE TITLE
Watch is not working with dynamic client

### ISSUE THREAD

**Issue by dbazhal** [openshift/openshift-restclient-python#203]
I have 0.7.1 client and I'm trying to make watch request.
This works:
```python
from openshift import watch
from openshift import client
from openshift.client import BuildOpenshiftIoV1Api

openshift_client = client.ApiClient()
build_api_client = BuildOpenshiftIoV1Api(openshift_client)
watcher = watch.Watch()
for event in watcher.stream(
    build_api_client.list_namespaced_build,
    namespace='my-test-namespace',
    field_selector='metadata.name={}'.format('my-test-buildname-3'),
    resource_version=0,
    timeout_seconds=600
):
    print(type(event))
```
and this is not:
```python
from openshift import watch
from openshift import dynamic
from openshift.dynamic import Resource

dyn_client = dynamic.DynamicClient()
dyn_build_api: Resource = dyn_client.resources.get(
    api_version='build.openshift.io/v1', kind='Build'
)
watcher = watch.Watch()
for event in watcher.stream(
    dyn_build_api.get,
    namespace='my-test-namespace',
    field_selector='metadata.name={}'.format('my-test-buildname-3'),
    resource_version=0,
    timeout_seconds=600
):
    print(type(event))
```
it never hits "print" because it makes it's first request on
/apis/build.openshift.io/v1/namespaces/my-test-namespace/builds?fieldSelector=metadata.name%3Dmy-test-buildname-3&resourceVersion=0&timeoutSeconds=600&watch=True and hangs waiting for it. I haven't been digging deeper, but I put print into kubernetes/client/api_client.py:317
```
print(resource_path, method,
                                   path_params, query_params, header_params,
                                   body, post_params, files,
                                   response_type, auth_settings,
                                   _return_http_data_only, collection_formats, _preload_content, _request_timeout)
```
and this is how working watch request looks like:
```
/apis/build.openshift.io/v1/namespaces/{namespace}/builds
GET {'namespace': 'my-test-namespace'}
[('fieldSelector', 'metadata.name=my-test-buildname-2'), ('resourceVersion', '0'), ('timeoutSeconds', 600), ('watch', True)]
{'Accept': 'application/json', 'Content-Type': 'application/json'}
None [] {} V1BuildList ['BearerToken', 'Oauth2AccessToken', 'Oauth2Implicit'] True {} False None
```
and this is how infinite waiting request looks like:
```
/apis/build.openshift.io/v1/namespaces/my-test-namespace/builds
GET {}
[('fieldSelector', 'metadata.name=my-test-buildname-3'), ('resourceVersion', '0'), ('timeoutSeconds', 600), ('watch', True)]
{'Accept': 'application/json', 'Content-Type': 'application/json'}
None [] {} None ['BearerToken'] True None False None
```
Looks loke dynamic client in some cases shouldn't render path with namespace built into it, but just proxy it as is to kubernetes api_client.

**Comment by fabianvf** [comment]
In the end those values just get templated into the URL when the request is made by the rest client, I think there may be something else going on. Watch predates the dynamic client pretty significantly so it may just be relying on invalid assumptions. Thanks for digging, I'm going to try and take a look at this later today and see if anything pops out at me.

**Comment by fabianvf** [comment]
Both good ideas, I'll definitely try to get the first one up today, the second when I can find some time. Thanks again for pointing out the issue and helping track it down!

**Comment by morsik** [comment]
This workaround doesn't works for me ;(

```python
def watch_namespaces(ctx):
    resource_version = 0

    while True:
        try:
            log.debug("Watching events for Namespace since resource_version=%d...",
                      resource_version)
            v1_projects = ctx.client.resources.get(api_version='project.openshift.io/v1',
                                                   kind='Project')
            from kubernetes import watch
            w = watch.Watch()
            for ev in w.stream(v1_projects.get,
                               serialize=False,
                               resource_version=resource_version,
                               timeout_seconds=60):

                print(ev)
                # do something real here

                try:
                    if resource_version < int(ev['object'].metadata.resource_version):
                        resource_version = int(ev['object'].metadata.resource_version)
                        log.debug("Updating resource_version to %d",
                                  resource_version)
                except TypeError:
                    pass

        except urllib3.exceptions.ReadTimeoutError:
            pass
```

This code indeed timeouts at 60 seconds, but no events appear. But `api.list_projects()` worked previously.

**Comment by fabianvf** [comment]
> After more testing, events works, but for unknown reason I don't see events since resource_version=0. It display events since starting app.

I'm not sure I follow this, I thought the expected behavior is that it would display all events occurring after you run the loop, are you expecting events from before the loop began to be ouput as well?

**Comment by morsik** [comment]
@fabianvf: since I'm specyfing `resource_version=0` it's obvious I want events before loop started.
This is how it works when you do `oc get <something> --watch` or when you do pure curl request with `&watch=true&resource_version=0`.

It works like this with old `watcher.stream(api.list_projects, ...)`

**Comment by fabianvf** [comment]
@morsik all right, figured it out, really dumb mistake on my part. Issue was that it checks if resource_version is set with `if params.get('resource_version')`, so if you provide resource_version 0 then it never sets it in the query string. Thanks for following up, I didn't realize that this behavior was incorrect.

**Comment by morsik** [comment]
@fabianvf: thank you! ;)
I updated my local virtualenv to this fix, and I can confirm it works now ;)
