### ISSUE TITLE
HELP -How to do get openshift token ?

### ISSUE THREAD

**Issue by zeyangli** [openshift/openshift-restclient-python#210]
I want to use python requests library to do. but I don't know how to do! Please help me!

    Thank you !

**Comment by fabianvf** [comment]
Hi @zeyangli ,

I'm not sure I follow the question, are you asking how to get an API token with which to authenticate to the OpenShift API?

**Comment by DenverJ** [comment]
Hi @zeyangli 

Do you mean to get an API token for a regular user? Not a service account? If so, I have written something to do this, using basic auth to authenticate. See https://gist.github.com/DenverJ/7bd44bc8b2d5e4b8e8a5cdf7bfee4d32

**Comment by zeyangli** [comment]
Thank you very much for solving my problem. I come from China. I am a beginner of openshift. I hope to learn more about openshift.




------------------ 原始邮件 ------------------
发件人: "Denver Janke"<notifications@github.com>;
发送时间: 2018年10月24日(星期三) 上午8:00
收件人: "openshift/openshift-restclient-python"<openshift-restclient-python@noreply.github.com>;
抄送: "李泽阳"<610556220@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [openshift/openshift-restclient-python] HELP -How to do getopenshift token ? (#210)




Hi @zeyangli
 
Do you mean to get an API token for a regular user? Not a service account? If so, I have written something to do this, using basic auth to authenticate. See https://gist.github.com/DenverJ/7bd44bc8b2d5e4b8e8a5cdf7bfee4d32
