### ISSUE TITLE
EKS authentication support

### ISSUE THREAD

**Issue by wvidana** [openshift/openshift-restclient-python#215]
There is an important change in the next kubernetes-client to fix AWS IAM authentication (used on EKS clusters).

When is the openshift client going to support next kubernetes-client/python version? https://github.com/kubernetes-client/python/issues/514#issuecomment-423311634

Is there any important changes to be added or just an update in requirements?

**Comment by fabianvf** [comment]
I think this should be a simple version bump in our dependencies, as far as I know there are no breaking changes in the next version of the kubernetes client. I'm happy to cut a new version as soon as the 8.0 client is released.

**Comment by greenbp** [comment]
Any chance we can get a new version out? 
https://github.com/kubernetes-client/python/issues/514#issuecomment-426366240

**Comment by wvidana** [comment]
This is already released, thank you :)
