### ISSUE TITLE
'How to login' section is missing from the README

### ISSUE THREAD

**Issue by cit1zen** [openshift/openshift-restclient-python#226]
I tried to use your library today, and I found the experience very awkward.

Most of API wrapper READMEs contain information about how to login to the API at the beginning of the usage section or at least link to the example with login.

There is `instantiated kubernetes client object`, but there is no explanation of how to create one.
Do I have to exec `oc login` before I use your library or is there a way how to do it using your library?

Could you add more explanation or examples of the login process?

**Comment by djzager** [comment]
Seems like a reasonable request. Admittedly though, `python-openshift` (especially the dynamic client) is intentionally relying on [kubernetes-client/python](https://github.com/kubernetes-client/python) to handle the  authentication/authorization piece. If you have a look at [kubernetes-client/python examples](https://github.com/kubernetes-client/python/#example) you may better understand how to proceed.

I trust @fabianvf more than myself so I welcome him to correct me if I am leading you astray. Regardless, I think the documentation could do better in this regard.

**Comment by fabianvf** [comment]
Yeah, totally reasonable request, thanks for the feedback. Not sure how I missed that, guess I've been working with it too long to tell what's confusing. 

I'm traveling at the moment but I'll try to tackle this soon after I get back (next Tuesday). If you hit any other sticking points trying to use it (either bad docs or bad implementation) definitely feel free to post more issues or comment here.
