### ISSUE TITLE
GET on DeploymentConfig resutls in 404

### ISSUE THREAD

**Issue by rummens** [openshift/openshift-restclient-python#243]
Hi there,

I am trying to retrieve a list of DeploymentConfigs of a project, but it failes with a Not Found 404. I tried calling the OpenShift REST API manually and it works. I guess something inside this tool calls the wrong API endpoint?

Here is the code:
```
v1_resources = self.dyn_client.resources.get(api_version='v1', kind="DeploymentConfig")
        try:
                # Lists all Services in the cluster
                return v1_resources.get(namespace=project)
```

Any suggestions?

Thanks
Kind Regards
Marcel

**Comment by djzager** [comment]
How are you instantiating the client? From the [README's usage section](https://github.com/openshift/openshift-restclient-python#usage):

To work with the dynamic client, you will need an instantiated Kubernetes
client object. The Kubernetes client object requires a Kubernetes Config
that can be set in the [Config
class](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py)
or using a helper utility.  All of the examples that follow make use of the
`new_client_from_config()` helper utility provided by the [Kubernetes Client
Config](https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py)
that returns an API client to be used with any API object.
There are plenty of [Kubernetes Client
examples](https://github.com/kubernetes-client/python/tree/master/examples) to
examine other ways of accessing Kubernetes Clusters.

When you say "calling the Openshift REST API manually" do you mean `oc get` or `curl`?

**Comment by rummens** [comment]
I was able to narrow the problem down to some issue with the label selector (using only app label in the moment). It works as excepted when I use the name of the deployment config. From my understanding the search with the labels should return an empty list if it does not find any resources (similar to Service).

@fabianvf I cannot give you the data, it seems dyn_client has to api_groups attribute or function? Returns with `AttributeError: 'DynamicClient' object has no attribute 'api_groups' `

**Comment by fabianvf** [comment]
Oh oops, `dyn_client.resources.api_groups`, apologies. If you aren't passing a name to get it should definitely be returning an empty list, not 404ing, I'll dig into that ASAP.

**Comment by rummens** [comment]
Hi, 
this is the response:
`dict_keys(['apps', 'authentication.k8s.io', 'autoscaling', 'batch', 'certificates.k8s.io', 'extensions', 'policy', 'storage.k8s.io'])
`

I found a workaorund for now, using the name and catching the exception. But it is not best practice :-) Thanks for your help

**Comment by fabianvf** [comment]
Cool, would you mind also posting the output of `dyn_client.version`?

**Comment by fabianvf** [comment]
Can I see the request you're making? I was able to perform a search with various combinations of `namespace`, `label_selector`, and `name`, and I got back empty lists as long as I did not provide name (if you provide name then it 404s, but that is expected).

**Comment by zebby76** [comment]
Hello,  Exactly same issue here : 

dyn_client.resources.api_groups : 

> dict_keys(['authentication.k8s.io', 'authorization.k8s.io', 'autoscaling', 'batch', 'certificates.k8s.io', 'extensions', 'policy', 'rbac.authorization.k8s.io', 'storage.k8s.io', 'apps', 'security.openshift.io', 'network.openshift.io', 'route.openshift.io', 'image.openshift.io', 'authorization.openshift.io', 'template.openshift.io', 'oauth.openshift.io', 'project.openshift.io', 'build.openshift.io', 'quota.openshift.io', 'user.openshift.io', 'apps.openshift.io'])

dyn_client.version : 

> {'kubernetes': {'major': '1', 'minor': '6', 'gitVersion': 'v1.6.1+5115d708d7', 'gitCommit': 'fff65cf', 'gitTreeState': 'clean', 'buildDate': '2018-11-25T08:15:14Z', 'goVersion': 'go1.7.6', 'compiler': 'gc', 'platform': 'linux/amd64'}, 'openshift': {'major': '3', 'minor': '6', 'gitCommit': '9686d5294b', 'gitVersion': 'v3.6.173.0.140', 'buildDate': '2018-11-25T08:15:14Z'}}

code : 

> dc = dyn_client.resources.get(api_version='v1', kind='DeploymentConfig')
> list = dc.get(namespace='mynamespace') 

> openshift.dynamic.exceptions.NotFoundError: 404                                                                                                                                                     
> Reason: Not Found                                                                                                                                                                                   
> HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Fri, 15 Feb 2019 16:25:56 GMT', 'Content-Length': '174'})                          
> HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}\n'

Note that the same issue occur when i specify a name like : 

> list = dc.get(name='mydeploymentconfig', namespace='mynamespace') 

Any suggestion of how to retrieve all deploymentconfig in my openshift namespace ?

Thanks.

**Comment by zebby76** [comment]
my fault, I misconfigured the client because I have to use the openshift as the version of the API.
the code below works perfectly well

`
dc = client.resources.get(api_version='apps.openshift.io/v1', kind='DeploymentConfig')
list = dc.get(name=name, namespace=namespace, label_selector=label_selector)
`

Anyway, thank you for this wonderful client !
