### ISSUE TITLE
ResourceNotFoundError for Openshift BuildRequest 

### ISSUE THREAD

**Issue by tomcooperca** [openshift/openshift-restclient-python#245]
Hi,
Not sure if this is the right repo to file this bug in. Running into this exception when attempting to create a `BuildRequest` object from a template/file via ansible `k8s_raw`. 

OCP 3.9
openshift (0.8.1)
ansible 2.6.4

My definition:

```
apiVersion: build.openshift.io/v1
kind: BuildRequest
metadata:
  name: "{{ appname }}"
  namespace: "{{ myapp.build.namespace }}"
triggeredBy:
  - message: "Manually triggered"
dockerStrategyOptions: {}
sourceStrategyOptions: {}
```

Traceback:

```
The full traceback is:
  File "/var/folders/s5/j618p8hd56g727l5hm116bgw0000gn/T/ansible_dFJyWH/ansible_modlib.zip/ansible/module_utils/k8s/common.py", line 190, in find_resource
    return self.client.resources.get(api_version=api_version, short_names=[kind])
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py", line 531, in get
    raise ResourceNotFoundError('No matches found for {}'.format(kwargs))

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": null
        }
    },
    "msg": "Failed to find exact match for build.openshift.io/v1.BuildRequest by [kind, name, singularName, shortNames]"
}
```

It seems to be a valid API object from poking around on my cluster's swagger specs. See below (from https://mycluster.example.com/apis/build.openshift.io/v1):

```json
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "build.openshift.io/v1",
  "resources": [
    {
      "name": "buildconfigs",
      "singularName": "",
      "namespaced": true,
      "kind": "BuildConfig",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ],
      "shortNames": [
        "bc"
      ],
      "categories": [
        "all"
      ]
    },
    {
      "name": "buildconfigs/instantiate",
      "singularName": "",
      "namespaced": true,
      "kind": "BuildRequest",
      "verbs": [
        "create"
      ]
    },
```

**Comment by fabianvf** [comment]
Thanks for the report and investigation!

On first look, it looks like this resource is violating one of the assumptions made by the dynamic client (namely that subresources for a kind will have the same kind), whereas here they have separated the subresource into it's own kind (`BuildRequest`). This is definitely a bug (there's a similar issue with OpenShift templates), but the fix for it is going to be rather involved, because it will require tweaking the base discovery logic and changing the data structure that stores discovered APIs. 

Unfortunately I don't have the bandwidth to pick this up right away (though it's definitely high up on the list), and I don't think there are any easy workarounds for it. I'm bringing up a cluster now to see if there's a more satisfying answer I can give you.

**Comment by fabianvf** [comment]
Actually it looks we are gathering it properly, so the issue instead is (I think) that it's a virtual resource backed by a subresource, rather than a regular resource, and the `k8s/k8s_raw/openshift_raw` modules only allow CRUD operations on more normal resources. Our approach to subresources thus far has been to create individual modules for them (ie, `k8s_scale`), but if this virtual resource pattern is present in other pieces of the API it may also make sense to add some detection of the pattern to the client. I'll try and investigate how difficult this would be soon.

**Comment by fabianvf** [comment]
>  It would be a shame to have to resort to doing a raw REST API call and/or a custom ansible module just to get the playbook equivalent of oc start-build....

I was actually talking about adding an official module to support builds that is released as part of core Ansible, though I'm definitely leaning towards direct support of this type of resource in the client (technically we do support build instantiation in the client, but as a method of a `BuildConfig` resource object rather than as the `BuildRequest` resource). I just need to verify there's no special behavior we need in addition to fixing the resource discovery bit.

**Comment by fabianvf** [comment]
@tomcooperca I posted a PR with some experimentation I was doing to get easy support for this kind of resource, haven't had much time to test it out yet but it seemed to work on cursory examination

**Comment by fabianvf** [comment]
@tomcooperca did you ever get a chance to try out the above PR?

**Comment by tomcooperca** [comment]
Sorry for the lack of follow up. I'll kick the tires on this in the next day or two.

**Comment by tomcooperca** [comment]
Looks like the client is getting a bit confused on which API it should target. When I navigate to my cluster's swagger docs, a `kind: BuildRequest` has two possible names. I assume the rest-client makes a decision based on the generated API docs on which URL it should target for which object type. I think it's choosing the wrong one. See outputs below:

Task:
```
    - name: Create a new Build from modified BuildConfig
      k8s:
        src: "{{ appname }}-buildrequest.yml"
        state: present
        namespace: "{{ namespace }}"
        verify_ssl: no
      register: new_build
```

Resource def:
```
apiVersion: build.openshift.io/v1
kind: BuildRequest
metadata:
  name: {{ appname }}
triggeredBy:
  - message: "Manually triggered via Ansible"
dockerStrategyOptions: {}
sourceStrategyOptions: {}
```

From https://console.mycluster.com/oapi/v1
```
{
  "kind": "APIResourceList",
  "groupVersion": "v1",
  "resources": [
    {
      "name": "buildconfigs/instantiate",
      "singularName": "",
      "namespaced": true,
      "kind": "BuildRequest",
      "verbs": [
        "create"
      ]
    },
    {
      "name": "builds/clone",
      "singularName": "",
      "namespaced": true,
      "kind": "BuildRequest",
      "verbs": [
        "create"
      ]
    }
...
```

Task output:
```
TASK [Create a new Build from modified BuildConfig] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "error": 403, "msg": "Failed to retrieve requested object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"builds.build.openshift.io \\\"choir-gds\\\" is forbidden: User \\\"system:serviceaccount:mynamespace:ansible\\\" cannot get builds.build.openshift.io/clone in the namespace \\\"mynamespace\\\": User \\\"system:serviceaccount:mynamespace:ansible\\\" cannot get builds/clone.build.openshift.io in project \\\"mynamespace\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"appname\",\"group\":\"build.openshift.io\",\"kind\":\"builds\"},\"code\":403}\n", "reason": "Forbidden", "status": 403}
```

Equivalent `oc` using the same token:
```
oc --token=eyJhbGciO... --loglevel=8 start-build appname
I0104 11:55:25.197807   41024 request.go:874] Request Body: {"kind":"BuildRequest","apiVersion":"build.openshift.io/v1","metadata":{"name":"appname","creationTimestamp":null},"triggeredBy":[{"message":"Manually triggered"}],"dockerStrategyOptions":{},"sourceStrategyOptions":{}}
I0104 11:55:25.197890   41024 round_trippers.go:414] POST https://console.mycluster.com:443/apis/build.openshift.io/v1/namespaces/mynamespace/buildconfigs/appname/instantiate

I0104 11:55:25.505996   41024 round_trippers.go:439] Response Status: 201 Created in 307 milliseconds
I0104 11:55:25.507316   41024 request.go:874] Response Body: {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"appname-7","namespace":"mynamespace","selfLink":"/apis/build.openshift.io/v1/namespaces/mynamespace/buildconfigs/appname-7/instantiate","uid":"882a4a7d-1041-11e9-a87a-0050568c3851","resourceVersion":"123135561","creationTimestamp":"2019-01-04T16:55:25Z","labels":{"app":"appname","buildconfig":"appname","openshift.io/build-config.name":"appname","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"appname","openshift.io/build.number":"7"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"appname","uid":"e7d41c86-deba-11e8-8291-0050568c0373","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"git@mygithub.com:repo.git","ref":"master"},"contextDir":"/src/main/docker/app","sourceSecret":{"name":"github-ssh"}},"strat [truncated 730 chars]
```

**Comment by fabianvf** [comment]
ah, that's a shame. In that case I think we might need to add a module to handle the `instantiate` subresource. It shouldn't be too difficult (`k8s_scale` is another module that implements interaction with a specific subresource). I'm a little pressed for time atm but I'll see if I can throw something up soon.

**Comment by tomcooperca** [comment]
Sounds good. If this issue is more appropriate on https://github.com/ansible/ansible wrt a custom module for OpenShift build operations, I'll be happy to open a new issue/feature request there and let us close this one out.

**Comment by fabianvf** [comment]
Yeah I think that would make sense, I think the plumbing is all working here, it's just not similar enough to a regular resource to handle from the generic CRUD module.

**Comment by tomcooperca** [comment]
👍 

thanks for verifying all on the client end. Will open a separate issue on ansible side.
