### ISSUE TITLE
Can not be installed on standard RHEL 7

### ISSUE THREAD

**Issue by pfuetz** [openshift/openshift-restclient-python#280]
when trying to install this openshift module via "pip install openshift", I do receive the following error messages:

[root@mpfuetzn openshift-restclient-python]# pip install openshift
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting openshift
  Using cached https://files.pythonhosted.org/packages/33/6b/76b2bb335e1721b7548cf194726dd6aec503e9e644cd44c9313317d334a7/openshift-0.8.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jXeFr0/openshift/setup.py", line 50, in <module>
        packages=find_packages(include='openshift.*'),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jXeFr0/openshift/
[root@mpfuetzn openshift-restclient-python]# 

I have no idea, if this is related to the older python version in RHEL 7, but everything else I tried, did not succeed.

pip is up-to-date:

[root@mpfuetzn openshift-restclient-python]# pip --version
pip 19.0.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)
[root@mpfuetzn openshift-restclient-python]# 

and also close to all modules are up to date:

[root@mpfuetzn openshift-restclient-python]# pip check
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
ipapython 4.6.4 has requirement python-ldap>=3.0.0b1, but you have python-ldap 2.4.15.
[root@mpfuetzn openshift-restclient-python]# 

Any ideas, what might be wrong here?

**Comment by fabianvf** [comment]
I think this is due to the version of `setuptools` available in rhel7. I believe there is a `python-openshift` RPM that's available in RHEL (though I'm not sure what repository it's in), and it should also be available in epel-release. If you specifically want to install it with pip on a rhel7 machine, I'd recommend creating a virtual environment with an updated version of setuptools (or install and use it from a container, which is what I generally do nowadays).

**Comment by pfuetz** [comment]
Thanks, that did the trick, and yes, it's in epel...

**Comment by pfuetz** [comment]
Aka: yum install python-openshift solved it
