### ISSUE TITLE
Add user to a project? 

### ISSUE THREAD

**Issue by mylespollie** [openshift/openshift-restclient-python#285]
I'm working on a project that provisions some OpenShift resources after a form is populated by a user.  First I create the project by doing the following:

```
project_to_create ='''
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  	name: example-project
'''

project_data = yaml.load(project_to_create)
response = v1_projects.create(body=project_data)
```

Now I'm trying to add a user to that created project.  This would be analogous to doing
```oadm policy add-role-to-user admin <user_name> -n <project_name>``` 

I'm struggling to find how to do this.  Any ideas? Thanks.

**Comment by fabianvf** [comment]
yeah, you'll need to create a rolebinding resource, which is all `oadm policy add-role-to-user` does under the hood. Here's an example of a rolebinding: https://github.com/fabianvf/game-server-operator/blob/master/deploy/role_binding.yaml

Also just to note, you don't need to yaml.load a string if you don't want to, the yaml.load just turns the string into a python dictionary so you could do something like

```
project = {'kind': 'Project', 'apiVersion': project.openshift.io/v1', 'metadata': {'name': 'example'} ...}
```

**Comment by fabianvf** [comment]
yeah, you'll need to create a rolebinding resource, which is all `oadm policy add-role-to-user` does under the hood. Here's an example of a rolebinding: https://github.com/fabianvf/game-server-operator/blob/master/deploy/role_binding.yaml

Also just to note, you don't need to yaml.load a string if you don't want to, the yaml.load just turns the string into a python dictionary so you could do something like

```
project = {'kind': 'Project', 'apiVersion': project.openshift.io/v1', 'metadata': {'name': 'example'} ...}
```
