### ISSUE TITLE
Error in installing openshift in cent os 7

### ISSUE THREAD

**Issue by rafiddewan** [openshift/openshift-restclient-python#309]
Got the following error:
TypeError: find_packages() got an unexpected keyword argument 'include'
Why is this here? My version for setuptools is 41.0.1 and I am running on pip 19.1.1

**Comment by fabianvf** [comment]
Interesting, is it possible there is an older, conflicting version of setuptools on the system that may be interfering?

**Comment by rafiddewan** [comment]
Was able to fix it, it was a configuration error
