### ISSUE TITLE
ERRROR: IOError: [Errno 2] No such file or directory, while using Ansible K8_facts plugin 

### ISSUE THREAD

**Issue by Vadanmehta** [openshift/openshift-restclient-python#311]
I am trying to run ansible playbook, usign K8_Facts plugin. kube_config.py gives IO Error[Errno 2] No such file or directory. 

Openshift RES T Client not able to load the config, ( see the line 503 of Kube_config.py) 

Ansible playbook, Log file & kube_config are attached.. 
[k8facts_log 1.txt](https://github.com/openshift/openshift-restclient-python/files/3330873/k8facts_log.1.txt)

**Comment by willthames** [comment]
Where is the kubernetes configuration supposed to come from?

I notice you're running ansible 2.7.0 - I know we fixed a bunch of kubernetes authorization bugs since that release - I'd strongly recommend upgrading to 2.8.1 or at least the latest 2.7 release
