### ISSUE TITLE
Bump requirement of kubernetes python client

### ISSUE THREAD

**Issue by machacekondra** [openshift/openshift-restclient-python#324]
Please bump kuberntes python client to 10.0.1. Version 10 brings few new features which may be useful for openshift client:
 https://github.com/kubernetes-client/python/blob/release-10.0/CHANGELOG.md#v1001

**Comment by pkliczewski** [comment]
@fabianvf can we please update the version? We need it to solve the [bug](https://bugzilla.redhat.com/1683151).

**Comment by pkliczewski** [comment]
@mmazur Please push a PR with the update

**Comment by mmazur** [comment]
https://github.com/openshift/openshift-restclient-python/pull/325

**Comment by mmazur** [comment]
Merged upstream, waiting for a release.

**Comment by fabianvf** [comment]
I cut an RC, https://pypi.org/project/openshift/0.10.0rc1/ , if anyone wants to try it out would be much appreciated. I'll cut the release later this week assuming that nothing is breaking

**Comment by bmillemathias-1a** [comment]
Issue can be closed.
