### ISSUE TITLE
How to access the scale part of a deploymentconfig

### ISSUE THREAD

**Issue by AlphaMalik** [openshift/openshift-restclient-python#375]
This is not an issue but a request for help
So I know how to get the deployment config from a namespace using the following code snippet:
`client.resources.get(api_version='apps.openshift.io/v1', kind='DeploymentConfig')`

What I would like to now do is modify the scale section of the DeploymentConfig... something to the effect of:
`PUT /apis/apps.openshift.io/v1/namespaces/$NAMESPACE/deploymentconfigs/$NAME/scale`

How do I go about doing that with the Python client?

**Comment by fabianvf** [comment]
Sorry for the delay, you should be able to access the scale subresource via the subresources dict or by calling it directly on the api resource, ie:

```
scale_body = {'kind': kind, 'metadata': {'name': name, 'namespace': namespace}, 'spec': {'replicas': replicas}}

dc_api =  client.resources.get(api_version='apps.openshift.io/v1', kind='DeploymentConfig')
print(dc_api.subresources) # This is the subresource dict
dc_api.scale.patch(body=scale_obj)
```
