### ISSUE TITLE
List Project Api call not working with  version 0.10.2

### ISSUE THREAD

**Issue by amay1212** [openshift/openshift-restclient-python#376]
While doing "List Projects" as given in README ,  [python list project's link](https://github.com/openshift/openshift-restclient-python#list-projects), getting below error as:-

**TypeError: type got multiple values for keyword argument 'prefix' in <script>** 

While debugging we found the following values in function `dyn_client.resources.get(api_version='project.openshift.io/v1', kind='Project')`

('prefix', 'apis')
('Subresources with name', None)
('resources are', {'kind': u'ProjectRequest',
 'name': u'projectrequests',
 'namespaced': False,
 'singularName': u'',
 'verbs': [u'create', u'list']})
('group', 'project.openshift.io')
('version', 'v1')
('client', <openshift.dynamic.client.DynamicClient object at 0x22c>)
('preferred', True)

Please note that this function was working fine with release 0.9.2

**Comment by fabianvf** [comment]
Sorry for the delay, I was not able to replicate this in 0.10.2 or 0.11.2, what version of openshift are you running against?
