### ISSUE TITLE
userpassauth.py missing after pip install

### ISSUE THREAD

**Issue by SakkeLate** [openshift/openshift-restclient-python#417]
Hi Folks

I Installed the module by executing 
`pip install openshift`
And executed the [example script](https://github.com/openshift/openshift-restclient-python#openshift-login-with-username-and-password)

The output was that userpassauth.py was not found... I manually copied the script from github and it started to work. So simple packaging issue?

Sorry, version was 0.12.1.

**Comment by jonespm** [comment]
It looks like this file is too new (commit in Sept 2021) and they haven't done a release since June 2021.

You could install master before the next release direct from Github like

`pip install --upgrade https://github.com/openshift/openshift-restclient-python/tarball/master`

**Comment by bhasterix** [comment]
@jonespm Thanks, that helped me. I'm having the same issue.
