### ISSUE TITLE
Failed to get client due to [digital envelope routines: EVP_DigestInit_ex] disabled for fips

### ISSUE THREAD

**Issue by Magoa** [openshift/openshift-restclient-python#427]
Info:
Using ansible community.kubernetes.k8s module, which uses this openshift python package, to run tasks on kubernetes.

Problem occurred using: 0.13.1
Workaround: Continue using 0.12.1

Have cluster that is FIPS compliant, noticed that while attempting to run k8s module tasks w/ updated openshift dependency, we would fail to deploy and have below error in logs.

`02:50:12 msg: 'Failed to get client due to [digital envelope routines: EVP_DigestInit_ex] disabled for fips'`

**Comment by venkataramanam** [comment]
Yes, it is confirmed that 0.13.1 has an issue.
0.12.1 works for us.

**Comment by venkataramanam** [comment]
This has now been resolved.
https://github.com/operator-framework/operator-sdk/issues/5723#issuecomment-1291597819
