### ISSUE TITLE
Failed to intall in python 2.7 - ruamel requests minimum python version 3.5

### ISSUE THREAD

**Issue by yongqianyang** [openshift/openshift-restclient-python#428]
Hi 
   I had a problem when install in my ubuntu with Python 2.7.17, it failed in resolving dependency, ruamel.yaml is requesting minimum python version 3.5,  

> $ cat /proc/version
> Linux version 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021
> 
> $ python setup.py install
> /usr/lib/python2.7/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '0.10.0dev1' to '0.10.0.dev1'
>   normalized_version,
> running install
> ......
> ......
> ......
> _Installed /usr/local/lib/python2.7/dist-packages/openshift-0.10.0.dev1-py2.7.egg
> Processing dependencies for openshift==0.10.0.dev1
> Searching for ruamel.yaml
> Reading https://pypi.python.org/simple/ruamel.yaml/
> Downloading https://files.pythonhosted.org/packages/46/a9/6ed24832095b692a8cecc323230ce2ec3480015fbfa4b79941bd41b23a3c/ruamel.yaml-0.17.21.tar.gz#sha256=8b7ce697a2f212752a35c1ac414471dc16c424c9573be4926b56ff3f5d23b7af
> Best match: ruamel.yaml 0.17.21
> Processing ruamel.yaml-0.17.21.tar.gz
> Writing /tmp/easy_install-GGWFG0/ruamel.yaml-0.17.21/setup.cfg
> Running ruamel.yaml-0.17.21/setup.py -q bdist_egg --dist-dir /tmp/easy_install-GGWFG0/ruamel.yaml-0.17.21/egg-dist-tmp-MOFrQy
> minimum python version(s): [(3, 5)]
> error: Setup script exited with 1_
>

**Comment by fabianvf** [comment]
This project (and the underlying kubernetes client) no longer support python 2 (which was EOLed in 2020). No additional work will be done to support python 2 as it would require changes not just to this project but to several dependencies (who have actively dropped python 2 support) as well. That being said I think the ruamel dependency is actually not necessary, you can probably just remove it from the requirements.

**Comment by yongqianyang** [comment]
OK, thanks for the info.
