### ISSUE TITLE
Unable to populate empty `subjects` element on a  RoleBinding

### ISSUE THREAD

**Issue by larsks** [openshift/openshift-restclient-python#435]
If we get or create a RoleBinding that has no subjects, we end up with the `obj.subjects == None`:

```
>>> body=dict(kind="RoleBinding", apiVersion="rbac.authorization.k8s.io/v1", metadata=dict(name="lars-test"), roleRef=dict(kind="ClusterRole", name="admin"), subjects=[])
>>> new = api.create(namespace='lars-sandbox', body=body)
>>> new.subjects
```

It doesn't appear to be possible to populate the `subjects` attribute:

```
>>> new.subjects = [dict(kind='User', name='larsks')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lars/.local/share/virtualenvs/openshift-acct-mgt-gsVIQrqs/lib64/python3.11/site-packages/kubernetes/dynamic/resource.py", line 348, in __setattr__
    self.attributes[name] = value
    ~~~~~~~~~~~~~~~^^^^^^
TypeError: 'ResourceField' object does not support item assignment
```

And since the value is `None`, we can't use e.g. `obj.subjects.append`, either.

Is the only solution to convert the object to a dictionary using `to_dict`, update the dict, then submit the modified dictionary in a `patch` request?

```
>>> updated = new.to_dict() | {"subjects": [{"kind": "User", "name": "larsks"}]}
>>> api.patch(body=updated,namespace='lars-sandbox')
```

**Comment by pr3sh** [comment]
Have you found any solution for this issue? I am currently facing the same error when trying to patch a deployment after updating it

**Comment by larsks** [comment]
@pr3sh the solution was essentially what I wrote at the end of my previous comment: convert the return value to a dictionary using the `to_dict` method, and from that point just operate on the dictionary version.

**Comment by pr3sh** [comment]
whenever I do that, i dont hit an error but there arent any subsequent changes to the resource (patch doesn't take effect)

**Comment by larsks** [comment]
/close

giving up on this one
