### ISSUE TITLE
Generated getting started documentation is wrong

### ISSUE THREAD

**Issue by fabianvf** [openshift/openshift-restclient-python#47]
https://github.com/openshift/openshift-restclient-python/blob/master/openshift/README.md#getting-started

Specifically, 
```python
api_instance = openshift.client.ApisApi()
```

raises `AttributeError: 'module' object has no attribute 'ApisApi'`

**Comment by detiber** [comment]
@fabianvf ah, good catch, since we are no longer generating objects that are in client-python this would no longer exist under openshift.client.

Will need to try and figure out how to handle updating or removing these items during generation or update the getting started section properly.

**Comment by mliker** [comment]
What is the correct way to instantiate the client then until the documentation is updated? I am also getting the above error.

**Comment by fabianvf** [comment]
If you need the ApisApi client I think you would just need to use the kubernetes client to access it. I have an open issue about investigating a clever way to make those apis accessible through the openshift client again.
