### ISSUE TITLE
Use kubernetes client-python models/api objects where possible

### ISSUE THREAD

**Issue by chekolyn** [openshift/openshift-restclient-python#5]
Hello Guys,

Thank you for creating a python client; it's very much needed. 
This is not an issue but just a suggestion that there is some upstream activity for a [python client](https://github.com/kubernetes-incubator/client-python). 
I would suggest that you take a look at it; there is a lot of work going on there. It might be easier to extend the library for the OpenShift API.

**Comment by detiber** [comment]
@chekolyn One of the goals of this project is to leverage [client-python](https://github.com/kubernetes-incubator/client-python) wherever possible.

We already use the following modules directly:
- kubernetes.client.configuration
- kubernetes.client.rest
- kubernetes.client.api_client

We are also re-using (with slight modifications) the generation scripts from client-python to build up the api and model modules, but we are currently generating the full API. Eventually, I'd like to see us build just the api and model modules that are not provided by client-python.

**Comment by chekolyn** [comment]
@detiber Thanks for the clarifying and looking forward to using this client.

**Comment by detiber** [comment]
Updating this issue to track supporting using the kubernetes client-python models and api objects where possible, instead of supplying our own.
