### ISSUE TITLE
Can't get resources by name

### ISSUE THREAD

**Issue by propyless** [openshift/openshift-restclient-python#58]
Hi,

Trying to for example pull a certain template with:
GET /oapi/v1/namespaces/{namespace}/templates/{name}

I don't think its possible or could just be me doing it wrong :)
```
def list_templates():
    namespace = 'openshift'
    pretty = 'pretty_example'
    watch = False

    try:
        api_response = api_instance.list_namespaced_template(namespace, pretty=pretty, watch=watch)
        pprint(api_response)
    except ApiException as e:
        print("Exception when calling OapiApi->list_namespaced_template: %s\n" % e)
```

will return everything. and I can't see anything in the documentation about there being a python binding to get something by name.

**Comment by chekolyn** [comment]
@propyless 

The function: list_namespaced_template will list all templates in the namespaces

The belive you want this function: 
**read_namespaced_template**(name="template name", namespace="namespace name" )
