### ISSUE TITLE
Unable to read Template Objects 

### ISSUE THREAD

**Issue by chekolyn** [openshift/openshift-restclient-python#60]
I'm not sure if this is an issue but I'm not able to see objects from a template; however this information is available in the raw json response.

The function that I'm using is this:
**read_namespaced_template()**

Somewhere in the response I get:
```
 'objects': [{'raw': None},
             {'raw': None},
             {'raw': None},
             {'raw': None},
             {'raw': None}],
```

I've observed this behavior when using this function as well: **list_namespaced_template()**

Is there a way to tap into this data?

**Comment by chekolyn** [comment]
I kind of answer my own question regarding tapping into the raw json data. Describing the method below.

We can use the following function: **read_namespaced_template_with_http_info** without preloading the content using **_preload_content=False**, then we can use json.load to read the first element of the returned tuple. 

For example:
```
(a, b, c) = oapi.read_namespaced_template_with_http_info(name=template_name, namespace=ns_name, _preload_content=False)

print json.load(a)
```

**Comment by btjd** [comment]
I have a similar issue with processing templates. Issuing the rest call works fine but making it through the client seems to be broken.

```
from openshift import config
from openshift import client as ocpclient
from kubernetes import client as k8sclient
from kubernetes.client.rest import ApiException
from pprint import pprint
import json

namespace = 'default'
pretty = 'pretty_example'

config.load_kube_config()

api = ocpclient.OapiApi()
with open('templates/fio.json') as jf:
    template_dict = json.load(jf)

try:
    processed_template_dict = api.create_namespaced_processed_template(namespace, template_dict, pretty=pretty)
    pprint(processed_template_dict)
except ApiException as e:
    print("Exception when calling OapiApi->create_namespaced_processed_template: %s\n" % e)
```

I get:

> Exception when calling OapiApi->create_namespaced_processed_template: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 04 Oct 2017 19:41:29 GMT', 'Content-Length': '174', 'Content-Type': 'application/json', 'Cache-Control': 'no-store'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

If I run the same code but using the method "create_processed_template_for_all_namespaces_v1" I get the following output:

> {'api_version': 'v1',
 'kind': 'Template',
 'labels': None,
 'message': None,
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': {},
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'name': 'fio',
              'namespace': None,
              'owner_references': None,
              'resource_version': None,
              'self_link': '/oapi/v1/namespaces//processedtemplates/fio',
              'uid': None},
 **'objects': [{'raw': None}, {'raw': None}, {'raw': None}, {'raw': None}],**
 'parameters': [{'_from': None,
                 'description': 'The name assigned to all of the frontend objects defined in this template.',
                 'display_name': 'Name',
                 'generate': None,
                 'name': 'NAME',
                 'required': True,
                 'value': 'fio'},
                {'_from': None,
                 'description': 'Volume space available for data, e.g. 512Mi, 2Gi',
                 'display_name': 'Volume Capacity',
                 'generate': None,
                 'name': 'VOLUME_CAPACITY',
                 'required': True,
                 'value': '1Gi'},
                {'_from': None,
                 'description': 'Storage class to create PVC from.',
                 'display_name': None,
                 'generate': None,
                 'name': 'STORAGECLASS_NAME',
                 'required': None,
                 'value': 'default'},
                {'_from': '[a-z0-9]{10}',
                 'description': 'Random string add on for PVC.',
                 'display_name': 'PVC String Add on',
                 'generate': 'expression',
                 'name': 'PVC_STRING',
                 'required': None,
                 'value': 'e55f5uhpmp'},
                {'_from': None,
                 'description': 'The file that you want downloaded that specifies FIO parameters.',
                 'display_name': 'FIO File',
                 'generate': None,
                 'name': 'FIO_FILE',
                 'required': None,
                 'value': 'https://gitlab.cee.redhat.com/mdunn/cns-dev/raw/master/apps/FIO/ini/fio.ini'}]}

Note that I get a correclty processed json template when using curl to exercise that endpoint.

**Comment by izapolsk** [comment]
I also ran into this serialization issue.

**Comment by izapolsk** [comment]
@fabianvf, could you please fix this bug with deserialization of RawExtension ?

As far as I see openshift's go scripts use the following in such case
https://github.com/openshift/origin/blob/a2ec32460a7351e6ddef482f995f375e99fdef25/pkg/template/apis/template/v1/zz_generated.conversion.go#L187

**Comment by fabianvf** [comment]
The [dynamic client](https://github.com/openshift/openshift-restclient-python/blob/master/README.md#dynamic-client-usage) that we added recently should handle this properly.
