### ISSUE TITLE
Issues with create_namespaced_image_stream_import()

### ISSUE THREAD

**Issue by awiddersheim** [openshift/openshift-restclient-python#66]
Been testing the [Ansible](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/guide_kubernetes.rst) modules with the following:

```
- name: import image stream
  openshift_v1_image_stream_import:
    namespace: "testing"
    name: "memcached"
    debug: yes
    images:
      - from:
          kind: "DockerImage"
          name: "docker.io/memcached:1.4-alpine"
        to:
          name: "1.4-alpine"
```

This kept failing however with the following:

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/xb/3zs_phrs0d3_yxn2692vlj3nncgz5_/T/ansible_BA8P4M/ansible_module_openshift_v1_image_stream_import.py", line 2390, in <module>
    main()
  File "/var/folders/xb/3zs_phrs0d3_yxn2692vlj3nncgz5_/T/ansible_BA8P4M/ansible_module_openshift_v1_image_stream_import.py", line 2384, in main
    module.execute_module()
  File "/var/folders/xb/3zs_phrs0d3_yxn2692vlj3nncgz5_/T/ansible_BA8P4M/ansible_modlib.zip/ansible/module_utils/k8s_common.py", line 153, in execute_module
  File "/var/folders/xb/3zs_phrs0d3_yxn2692vlj3nncgz5_/T/ansible_BA8P4M/ansible_modlib.zip/ansible/module_utils/openshift_common.py", line 53, in _create
  File "/var/folders/xb/3zs_phrs0d3_yxn2692vlj3nncgz5_/T/ansible_BA8P4M/ansible_modlib.zip/ansible/module_utils/k8s_common.py", line 235, in _create
  File "~/.virtualenvs/foobar/lib/python2.7/site-packages/openshift/helper/base.py", line 227, in create_object
    create_method(namespace, body=body)
TypeError: create_namespaced_image_stream_import() got multiple values for keyword argument 'body'
```

Looks like the generated content for these function signatures in [oapi_api.py](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/client/apis/oapi_api.py) has the arguments flipped if I'm understanding things correctly. I believe it is getting called [here](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/helper/base.py#L240).

Currently is this:

```
def create_namespaced_image_stream_import(self, body, namespace, **kwargs):
```

Should be:

```
def create_namespaced_image_stream_import(self, namespace, body, **kwargs):
```

After I changed those around I got a bit further but started to hit this:

```
Failed to create object: Error: method read_namespaced_image_stream_import not found for model image_stream_import.
```

**Comment by awiddersheim** [comment]
Digging into the second error:

```
Failed to create object: Error: method read_namespaced_image_stream_import not found for model image_stream_import.
```

This comes from [`lookup_method()`](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/helper/base.py#L403-L429). Looks like after each action (create, delete, replace, etc), the module will then read back the items from the API. However, [imagestreamimport](https://docs.openshift.com/container-platform/3.5/rest_api/openshift_v1.html#create-an-imagestreamimport) doesn't have an endpoint where you can `GET` the imported image streams. I think you'd use [`/oapi/v1/imagestreams`](https://docs.openshift.com/container-platform/3.5/rest_api/openshift_v1.html#list-or-watch-objects-of-kind-imagestream)

I think there are other methods like this as well where you can create an object in the REST API but there is no way to `GET` them back or you would use a separate endpoint that the helper modules don't know about or cant' find.

**Comment by jcpowermac** [comment]
I have also seen this issue

**Comment by fabianvf** [comment]
I've regenerated the modules, are you still seeing this issue?

**Comment by djzager** [comment]
Looks like we'll have to handle these types of actions differently based on https://github.com/openshift/openshift-restclient-python/issues/66#issuecomment-313405107.

**Comment by fabianvf** [comment]
The new [dynamic client](https://github.com/openshift/openshift-restclient-python/blob/master/README.md#dynamic-client-usage) should be able to handle this case.
