### ISSUE TITLE
[helper] Add support for supplying full yaml/json for objects/sub-objects.

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-restclient-python#7]
Add an "advanced" mode that would allow specifying the full yaml/json for the object or for properties of an object.

**Comment by chekolyn** [comment]
@detiber I'm not sure if this is related but I'm having a hard time reading objects from a template. 
I've expanded a little bit more in this issue #60

**Comment by fabianvf** [comment]
The dynamic client accepts yaml definitions.
