### ISSUE TITLE
Consider making src come from templates

### ISSUE THREAD

**Issue by awiddersheim** [openshift/openshift-restclient-python#76]
Currently, it's possible to specify [`src`](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/helper/ansible.py#L135-L141) which allows loading a definition from a file. This gets loaded just as a [plain file](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/k8s_common.py#L250-L261).

I think it would be better if this acted more like how some of the Ansible network modules work where `src` gets treated as a template. I'm guessing that the way people will use these Openshift/Kubernetes modules will be very similar to how people use the network modules. For example [vyos_config](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/vyos/vyos_config.py) and [asa_config](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/asa/asa_config.py).

The template handling for these network modules all happens through Ansible's Action Plugins. A few examples can be found [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/net_config.py) and [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/vyos_config.py).

Here are a few [links](https://www.ansible.com/blog/how-to-extend-ansible-through-plugins) to [documentation](http://ndemengel.github.io/2015/01/20/ansible-modules-and-action-plugins/) about Ansbile's Action Plugins.

This would take some changes to the upstream `k8s_common.py` module in Ansible but judging by how the network action plugins are setup, it looks like there should be an action generated for each module here possibly deriving all from a single class as is done with `net_config`. I'm just speculating around the best approach here.

**Comment by brennv** [comment]
It looks like we might be able to move forward on this with: https://github.com/ansible/ansible/pull/27833

For reference `k8s_common.py` has been [removed](https://github.com/ansible/ansible-kubernetes-modules/commit/2fa7e4234fb1003587481d3e793f74582fe48c7f) from [ansible/ansible-kubernetes-modules](https://github.com/ansible/ansible-kubernetes-modules) as discussed [here](https://github.com/ansible/ansible-kubernetes-modules/pull/4).

**Comment by fabianvf** [comment]
We have been using `definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"` to get this functionality, if you still want to propose having src do jinja templating, open up an issue against Ansible for the [k8s module](https://docs.ansible.com/ansible/devel/modules/k8s_module.html)
