### ISSUE TITLE
Default kube config not being picked up

### ISSUE THREAD

**Issue by HCanber** [openshift/openshift-restclient-python#81]
In 0.0.1 if auth options are set, specifying how to connect to kubernetes, the default config `~/.kube/config` (or the one specified in `KUBECONFIG`) was picked up and used.

The commit 13d5d86ca89035b9f596032e7a34f3cc33bf8f18 broke this. The only way to use a config file now is to explicitly specify one in `kubeconfig`.

---

I guess the proper way to handle this in [KubernetesObjectHelper.client_from_config](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/helper/kubernetes.py#L18) is:

- If `config_file` is not set, and a default config file does not exist, then `return ApiClient(config=ConfigurationObject())`

This is how [load_kube_config](https://github.com/kubernetes-client/python-base/blob/824c03c7eee71dd5ac52fada8d7d36aecf81a781/config/kube_config.py#L333) determines which file to use:

``` python
KUBE_CONFIG_DEFAULT_LOCATION = os.environ.get('KUBECONFIG', '~/.kube/config')

if config_file is None:
  config_file = os.path.expanduser(KUBE_CONFIG_DEFAULT_LOCATION)
```

**Comment by fabianvf** [comment]
Good catch, nice solution. Will get this in ASAP
