### ISSUE TITLE
Allow to create "CustomResourceDefinition"

### ISSUE THREAD

**Issue by gbenhaim** [openshift/openshift-restclient-python#83]
Currently, only ```ThirdPartyResource``` are supported, which is deprecated in kubernetes 1.7

**Comment by fabianvf** [comment]
It looks like CustomResourceDefinitions will be included in python [kubernetes 4.0.0](https://github.com/kubernetes-incubator/client-python/blob/release-4.0/kubernetes/client/models/v1beta1_custom_resource_definition.py) which is aligned to kube 1.8. If you're talking about via the ansible modules, when we regenerate the modules against 4.0.0/1.8 we should pull it in.

**Comment by fabiand** [comment]
@fabianvf when will the ansible modules be recreated?

Could we wait with closing the bug until the bug is fixed?

**Comment by djzager** [comment]
https://github.com/openshift/openshift-restclient-python/issues/147
