### ISSUE TITLE
Module generation broken for openshift 3.6+

### ISSUE THREAD

**Issue by fabianvf** [openshift/openshift-restclient-python#88]
The naming schemes for kubernetes and openshift resources in the swagger spec now have the full package name, which makes the generated module names really long, and also breaks compatibility with the kubernetes client (which has changed it's whole generation method, it now has a single repo that runs a container that generates the modules). This blocks #85

**Comment by gbenhaim** [comment]
What exactly is broken?
The Python SDK, the Ansible modules or both?

**Comment by fabianvf** [comment]
The generation of the python SDK (and by extension the ansible modules). With 3.6.0 it looks like they changed the way the resources/definitions were named to include the fully qualified name (com.github.openshift.origin.[..].v1.project). The kubernetes client generator has already accounted for these changes, so I'm looking at leveraging their work a bit more.
