### ISSUE TITLE
Getting errors with the latest version

### ISSUE THREAD

**Issue by danmcp** [openshift/openshift-restclient-python#93]
Collecting openshift (from pman==1.4.0)
  Downloading openshift-0.3.0.tar.gz (297kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-70b52emt/openshift/setup.py", line 49, in <module>
        install_requires=extract_requirements('requirements.txt'),
      File "/tmp/pip-build-70b52emt/openshift/setup.py", line 36, in extract_requirements
        with open(filename, 'r') as requirements_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by fabianvf** [comment]
that's not good...  A release should not have gone out yet.

**Comment by fabianvf** [comment]
@danmcp I pushed a new version to pypi that should work correctly now, and I fixed the bug that caused a version to be pushed in the first place. Let me know if you are still seeing issues.

**Comment by danmcp** [comment]
@fabianvf Working now. Thanks!
