### ISSUE TITLE
BuildConfig spec_node_selector does not map to a module parameter

### ISSUE THREAD

**Issue by sterburg** [openshift/openshift-restclient-python#96]
## task definition
- name: "Define OpenShift BuildConfig"
  openshift_v1_build_config:
    namespace: "{{ namespace }}"
    verify_ssl: False
    resource_definition:
      metadata:
        creationTimestamp: null
        labels:
          app: "{{ project_name }}"
        name: "{{ project_name }}"
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: "{{ project_name }}:latest"
        postCommit: {}
        resources: {}
        source:
          git:
            uri: "https://{{ vsts_instance }}.visualstudio.com/_git/{{ project_name }}"
            sourceSecret:
              name: git
          type: Git
        strategy:
          sourceStrategy:
            from:
              kind: ImageStreamTag
              name: nodejs:6
              namespace: openshift
          type: Source
        triggers:
        - github:
            secret: 8kdCwBdWpup5OydYqXCj
          type: GitHub
        - generic:
            secret: wuve0D41bIFHPU_DzT5-
          type: Generic
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange

## playbook execution result 
TASK [provision-visualstudio-project : Define OpenShift BuildConfig] ***********
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error parsing resource definition. Encountered spec_node_selector, which does not map to a module parameter. If this looks like a problem with the module, please open an issue at github.com/openshift/openshift-restclient-python/issues"}
        to retry, use: --limit @/opt/apb/actions/provision.retry

**Comment by hhenkel** [comment]
I'm currently toying around with version 0.4.4 and I'm seeing the same issue. I investigated a bit and it seems it is a value error. According to the [docs](https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-assigning-builds-to-nodes) node selector awaits a key/value pairs. The [pyhon restclient](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/client/models/v1_build_config_spec.py#L36) also awaits a dict. 

The provided sample data only provides one value (null) and does therefore not match.

From what I saw so far it seems `nodeSelector: null` has its origin from a export of the BuildConfig resource in Openshift (at least that's how I ended up with it).

**Comment by hhenkel** [comment]
When creating a build config without the node selector value, the result also contains the `"node_selector": null` field:

```
    "result": {
        "api_version": "v1",
        "kind": "BuildConfig",
        "metadata": {
            "annotations": null,
            "cluster_name": null,
            "creation_timestamp": "2018-03-09T14:51:59+00:00",
            "deletion_grace_period_seconds": null,
            "deletion_timestamp": null,
            "finalizers": null,
            "generate_name": null,
            "generation": null,
            "initializers": null,
            "labels": null,
            "name": "reposync",
            "namespace": "contenthost",
            "owner_references": null,
            "resource_version": "9526327",
            "self_link": "/oapi/v1/namespaces/contenthost/buildconfigs/reposync",
            "uid": "6bb1cfca-23a9-11e8-8978-005056a6a7cd"
        },
        "spec": {
            "completion_deadline_seconds": null,
            "failed_builds_history_limit": null,
            "node_selector": null,
            "output": {
                "image_labels": null,
                "push_secret": null,
                "to": {
                    "api_version": null,
                    "field_path": null,
                    "kind": "ImageStreamTag",
                    "name": "reposync:latest",
                    "namespace": null,
                    "resource_version": null,
                    "uid": null
                }
            },
```

`oc create -f buildconfig.yml` works as expected - therefore the question is (to my understanding) how to handle `null` values when trying to map data to api calls that expect more complicated data.

**Comment by fabianvf** [comment]
The new [dynamic client](https://github.com/openshift/openshift-restclient-python/blob/master/README.md#dynamic-client-usage) and corresponding [k8s module](https://docs.ansible.com/ansible/devel/modules/k8s_module.html) should be able to handle this properly.
