### ISSUE TITLE
ImageStream.spec.lookupPolicy has no module parameter mapping

### ISSUE THREAD

**Issue by sterburg** [openshift/openshift-restclient-python#97]
## Task definition
- name: "Define OpenShift ImageStream"
  openshift_v1_image_stream:
    namespace: "{{ namespace }}"
    verify_ssl: False
    resource_definition:
      metadata:
        creationTimestamp: null
        labels:
          app: "{{ project_name }}"
        name: "{{ project_name }}"
      spec:
        lookupPolicy:
          local: false

## playbook execution result
TASK [provision-visualstudio-project : Define OpenShift ImageStream] ***********
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error parsing resource definition. Encountered spec_lookup_policy_local, which does not map to a module parameter. If this looks like a problem with the module, please open an issue at github.com/openshift/openshift-restclient-python/issues"}
        to retry, use: --limit @/opt/apb/actions/provision.retry

## remark
Removing the "spec.lookupPolicy" fixes it and object is being created.
So it looks like there is no or an incorrect mapping on this lookupPolicy attribute.

**Comment by leifmadsen** [comment]
This might not be an issue any more because I don't see that error with a template that has a call like this with Ansible Service Broker in Origin 3.9.

**Comment by fabianvf** [comment]
The new [dynamic client](https://github.com/openshift/openshift-restclient-python/blob/master/README.md#dynamic-client-usage) and corresponding [k8s module](https://docs.ansible.com/ansible/devel/modules/k8s_module.html) should be able to handle this properly.
