### ISSUE TITLE
BuildConfig: spec_strategy_source_strategy_from_kind  does not map to a module parameter.

### ISSUE THREAD

**Issue by sterburg** [openshift/openshift-restclient-python#99]
## task definition
- name: "Define OpenShift BuildConfig"
  openshift_v1_build_config:
    namespace: "{{ namespace }}"
    verify_ssl: False
    resource_definition:
      metadata:
        creationTimestamp: null
        labels:
          app: "{{ project_name }}"
        name: "{{ project_name }}"
      spec:
        output:
          to:
            kind: ImageStreamTag
            name: "{{ project_name }}:latest"
        postCommit: {}
        resources: {}
        source:
          git:
            uri: "https://{{ vsts_instance }}.visualstudio.com/_git/{{ project_name }}"
            sourceSecret:
              name: git
          type: Git
        strategy:
          sourceStrategy:
            from:
              kind: ImageStreamTag
              name: nodejs:6
              namespace: openshift
          type: Source
        triggers:
        - github:
            secret: 8kdCwBdWpup5OydYqXCj
          type: GitHub
        - generic:
            secret: wuve0D41bIFHPU_DzT5-
          type: Generic
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
      status:
        lastVersion: 0

## playbook execution result
TASK [provision-visualstudio-project : Define OpenShift BuildConfig] ***********
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error parsing resource definition. Encountered spec_strategy_source_strategy_from_kind, which does not map to a module parameter. If this looks like a problem with the module, please open an issue at github.com/openshift/openshift-restclient-python/issues"}
        to retry, use: --limit @/opt/apb/actions/provision.retry

## remarks
All i did was take the output of `oc new-app https://github.com/openshift/nodejs-ex.git -o yaml` and tried to put it in an APB.
Would be good to have some test-cases that test *ALL* possible attributes of *ALL* possible objects.

**Comment by fabianvf** [comment]
hmm, it seems that it maps to is ` spec_strategy_source_strategy__from_kind`, probably because somewhere `from` is being replaced with `_from` for python compatibility. Will look into this.

**Comment by fabianvf** [comment]
to follow up though, does adding the extra underscore fix this problem for you?
